### PR TITLE
Renamed appconfig to manifest

### PR DESCRIPTION
**Pull request by Kyrremann**
Got a little bit irritated that we used both the name `appconfig` and `manifest`. `manifest` is the new and correct way.

### CODE REVIEW

**Comment by davidsteinsland** [comment]
Will there be a grace period here, where this will be rolled out to preprod clusters first? I am assuming everyone using the `nais deploy` cmd / curl or JIRA Auto Deploy will have to update their code

**Comment by Kyrremann** [comment]
If they are sending in a different yaml then what's in Nexus, they need to update. The only external thing that is changing is the REST-endpoint `/deploy` and the argument `appconfigurl=`, which will be `manifesturl=` from now. Grace periode is possible.

The normal flow of a cURL call is to use the default, which retrieves from Nexus.

**Comment by audunstrand** [comment]
I agree with david.need to use expand contract here to maintain backwards compabilty. 

Also I feel that that word app adds meaning. 
appManifest

**Comment by audunstrand** [comment]
I also agree on changing function names as well as variables

**Comment by Kyrremann** [comment]
We can implement a deprecation periode, where we can have both fields, and use the one that is not empty?

@audunstrand can change to `appManifest`, but I@m hoping we don't need more manifests, so that having just one is self explanatory.

**Comment by Kyrremann** [comment]
@davidsteinsland thoughts on deprecation period? Use both for the next week? So removed it the 1th of February.

**Comment by davidsteinsland** [comment]
@Kyrremann sounds good 👍🏻

**Pull request merged**
