### PR TITLE
Cli

### PR DESCRIPTION
**Pull request by audunstrand**
First try at nais CLI.
Validates appconfig in current directory, or another file using --file
Usage 
> nais validate

### CODE REVIEW

**Comment by audunstrand** [comment]
I dont yet understand how we should distribute the binary in a efficient manner

**Comment by gtcno** [comment]
Top of my head: 

Link to binary in github naisd?

**Comment by audunstrand** [comment]
so build in travis, then check in the binary on a release tag?

**Comment by jhrv** [comment]
👌

**Pull request merged**
